# Generated by Django 5.0.1 on 2024-01-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=45)),
                ('UserPass', models.CharField(max_length=45)),
                ('UserMail', models.CharField(max_length=45, null=True)),
                ('Loged_in', models.BooleanField(null=True)),
                ('user_Token', models.CharField(max_length=45, null=True)),
                ('toke_exp', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id_device', models.CharField(primary_key=True, serialize=False)),
                ('Model', models.CharField(max_length=45)),
                ('Waranty', models.DateField(null=True)),
                ('Number', models.IntegerField(null=True)),
                ('Status', models.CharField(max_length=45, null=True)),
                ('Assigned', models.BooleanField(null=True)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.device_type')),
                ('last_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Id_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Area', models.CharField(max_length=45)),
                ('Mail', models.CharField(max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('last_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_device',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('Assig_date', models.DateField(null=True)),
                ('Fin_date', models.DateField(null=True)),
                ('id_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.devices')),
                ('id_employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.employees')),
                ('last_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users')),
            ],
        ),
        migrations.AddField(
            model_name='device_type',
            name='last_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users'),
        ),
    ]
